name: Checks and Linters

on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: lidofinance/linters/.github/actions/lint-security@fix-codeql
        with:
          skip-codeql: true

      - uses: lidofinance/linters/.github/actions/lint-security@fix-codeql
        with:
          skip-codeql: false

  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master

  formatting:
    name: Check code formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      - name: Setup prettier
        run: npm install prettier

      - name: Check formatting with prettier
        run: npx prettier --check .
