name: Checks and Linters

on: 
  push:

jobs:
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
  
  docker:
    name: Check docker issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find all Dockerfiles
        shell: bash
        run: echo "::set-output name=dockerfiles::$(find . -name "Dockerfile" | xargs echo | sed 's/\.\///g')"
        id: get_df
      - uses: lidofinance/linters/.github/actions/lint-docker@master
        with:
          dockerfile: ethereum/Dockerfile polygon/Dockerfile
      - uses: lidofinance/linters/.github/actions/lint-docker@master
        with:
          dockerfile: ${{ steps.get_df.outputs.dockerfiles }}
