name: Checks and Linters

on: 
  push:

jobs:
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
  
  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master
