---
name: Tests @ l2-bridge-arbitrum

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "l2-bridge-arbitrum/**"

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
    with:
      path: ./l2-bridge-arbitrum
    secrets: inherit
