---
name: Tests @ ethereum-huge-tx

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "ethereum-huge-tx/**"

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
    with:
      path: ./ethereum-huge-tx
    secrets: inherit
