---
name: Tests @ ethereum-governance

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "ethereum-governance/**"

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
    with:
      path: ./ethereum-governance
    secrets: inherit
