---
name: Tests @ ethereum-validators-set

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "ethereum-validators-set/**"

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
    with:
      path: ./ethereum-validators-set
    secrets: inherit
