---
name: Tests @ ethereum-operations

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "ethereum-operations/**"

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
    with:
      path: ./ethereum-operations
    secrets: inherit
