---
name: Tests @ reverted-tx-watcher

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "reverted-tx-watcher/**"

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
    with:
      path: ./reverted-tx-watcher
    secrets: inherit
