---
name: Tests @ ethereum-steth

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "ethereum-steth/**"

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
    with:
      path: ./ethereum-steth
    secrets: inherit
